export const topPick = [
  {
    id: "1",
    title: "TOP GUN MAVERICK",
    maingenre: "Action",
    subgenre: "Drama",
    duration: "2h 10min",
    img: "https://m.media-amazon.com/images/I/81j8pjiDyfL.jpg",
  },
  {
    id: "2",
    title: "RAMPAGE",
    maingenre: "Adeventure",
    subgenre: "Action/Sci-Fi",
    duration: "1h 47min",
    img: "https://images.hungama.com/c/1/ac9/2e1/37326384/37326384_1280x800.jpg",
  },
  {
    id: "3",
    title: "BORN TO FLY",
    maingenre: "Action",
    subgenre: "Drama",
    duration: "2h 8min",
    img: "https://variety.com/wp-content/uploads/2022/10/Born-to-Fly-1.jpg",
  },
  {
    id: "4",
    title: "INCEPTION",
    maingenre: "Sci-Fi/Adventure",
    subgenre: "Action",
    duration: "2h 28min",
    img: "https://hdwallsource.com/img/2016/6/inception-movie-computer-wallpaper-49336-51002-hd-wallpapers.jpg",
  },
  {
    id: "5",
    title: "FAST AND FURIOUS",
    maingenre: "Action",
    subgenre: "Adeventure/Crime",
    duration: "2h 21min",
    img: "https://images6.alphacoders.com/131/1319315.jpeg",
  },
  {
    id: "5",
    title: "THE COVENANT",
    maingenre: "Action",
    subgenre: "Drama/Thriller",
    duration: "2h 3min",
    img: "https://static1.colliderimages.com/wordpress/wp-content/uploads/2023/04/guy-ritchie-s-the-covenant-jake-gyllenhaal-dar-salim.jpg",
  },
];
